import {Inter} from 'next/font/google'
import { Providers as ThemeProvider } from "./providers/ThemeProvider"


const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} bg-slate-50 dark:bg-gray-900`}>
        <ThemeProvider>
            {children}
        </ThemeProvider>
        </body>
        </html>
    )
}