import {Inter} from 'next/font/google';
import Navbar from "@/app/components/navigation/Navbar";
import {Providers} from './providers'
import Footer from "@/app/components/footer/Footer";
import styles from "./styles/globals.css";

const inter = Inter({subsets: ['latin']});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning={true} data-lpignore="true">
        <body>
        <Providers>
            <Navbar/>
            {children}
            <Footer/>
        </Providers>
        </body>
        </html>
    );
}